version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.new
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    environment:
      - PM_APP_URL
      - PM_APP_PORT
      - PM_BROADCASTER_PORT
    volumes:
      - ${PM_DOCKER_SOCK}:/usr/bin/docker.sock
      - storage:/code/pm4/storage
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis
  redis:
    image: redis
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: processmaker
      MYSQL_USER: pm
      MYSQL_PASSWORD: pass
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
  storage:
